### PR TITLE
Various stuffs

### PR DESCRIPTION
**Pull request by epiquiem**
Hello again, @frap129.

Some various things I personally like to add.

### CODE REVIEW

**Comment by frap129** [comment]
Hey there! I cant add these sync this isnt my fork, but just a few things. The One already has a huge battery, so we dont need the battery saving on by default because it hinders speed. Second, how did you add all the TCP govs without changing anything other than defconfig?

**Comment by epiquiem** [comment]
I didn't think of the existing huge battery, I don't have an OPO yet :(
As for the TCP algorithms, most of them already exist in [this directory](https://github.com/YoshiShaPow/green_machine_bacon/tree/cm-12.0-TGM/net/ipv4); however they weren't enabled in the config by default for whatever reason.

**Comment by frap129** [comment]
Also, incase you didnt notice, there is a "tgm_bacon_defconfig" which replaced the Cyanogen one, but thanks for the commits! Ive been looking to add TCP govs but i didnt realize they were in there already.

**Comment by frap129** [comment]
Also, incase you didnt notice, there is a "tgm_bacon_defconfig" which replaced the Cyanogen one, but thanks for the commits! Ive been looking to add TCP govs but i didnt realize they were in there already.

**Comment by epiquiem** [comment]
Oh. oops.

**Comment by YoshiShaPow** [comment]
There's been talk between dev that multi core power saving hurts more than it helps...

**Comment by YoshiShaPow** [comment]
Also, the default gov us set from the ramdisk like most cm devices. The real default give is smartmax

**Comment by YoshiShaPow** [comment]
Thanks though! Will look into more tcps and io options

**Pull request closed without merging**
